### PR TITLE
fix: break the link of metadata server to Talos machine config

### LINKED ISSUE #1076: Sidero panics when serving metadata
I've been struggling to provision some servers as they would get stuck when trying to fetch their metadata.

It looks like this is because Sidero panics when attempting to serve said metadata.

```
2023/03/09 21:13:54 HTTP GET /boot.ipxe 127.0.0.1:52260
2023/03/09 21:13:54 received metadata request for uuid: 4c4c4544-0054-3510-8057-c7c04f424232
2023/03/09 21:13:54 http: panic serving 10.5.0.1:58686: runtime error: invalid memory address or nil pointer dereference
goroutine 34661 [running]:
net/http.(*conn).serve.func1()
        /toolchain/go/src/net/http/server.go:1850 +0xbf
panic({0x17643a0, 0x28cbbc0})
        /toolchain/go/src/runtime/panic.go:890 +0x262
github.com/siderolabs/sidero/app/sidero-controller-manager/internal/metadata.labelNodes({0xc000b78000, 0x1657, 0x1b00}, {0xc0003120f0, 0x24})
        /src/app/sidero-controller-manager/internal/metadata/metadata_server.go:297 +0x165
github.com/siderolabs/sidero/app/sidero-controller-manager/internal/metadata.(*metadataConfigs).FetchConfig(0xc0003ac260, {0x1c1eb20, 0xc00055e9a0}, 0xc0003d2700?)
        /src/app/sidero-controller-manager/internal/metadata/metadata_server.go:228 +0x5f2
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1c1eb20?, 0xc00055e9a0?}, 0x203000?)
        /toolchain/go/src/net/http/server.go:2109 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc00072c8e0?, {0x1c1eb20, 0xc00055e9a0}, 0xc0003d2700)
        /toolchain/go/src/net/http/server.go:2487 +0x149
main.main.func7.1({0x1c1eb20?, 0xc00055e9a0?}, 0xc000d0b2c0?)
        /src/app/sidero-controller-manager/main.go:307 +0xa5
net/http.HandlerFunc.ServeHTTP(0x203000?, {0x1c1eb20?, 0xc00055e9a0?}, 0xc00055e9a0?)
        /toolchain/go/src/net/http/server.go:2109 +0x2f
golang.org/x/net/http2/h2c.h2cHandler.ServeHTTP({{0x1c0b700?, 0xc0003be1c8?}, 0xc0006a6000?}, {0x1c1eb20, 0xc00055e9a0}, 0xc0003d2700)
        /.cache/mod/golang.org/x/net@v0.4.0/http2/h2c/h2c.go:125 +0x59b
net/http.serverHandler.ServeHTTP({0xc000d0b260?}, {0x1c1eb20, 0xc00055e9a0}, 0xc0003d2700)
        /toolchain/go/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc0003e9360, {0x1c1fcb8, 0xc0006703f0})
        /toolchain/go/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
        /toolchain/go/src/net/http/server.go:3102 +0x4db
```

```
2023/03/09 21:14:23 received metadata request for uuid: 4c4c4544-0047-4410-8034-b9c04f575631
2023/03/09 21:14:23 http: panic serving 10.5.0.1:48912: runtime error: invalid memory address or nil pointer dereference
goroutine 34769 [running]:
net/http.(*conn).serve.func1()
        /toolchain/go/src/net/http/server.go:1850 +0xbf
panic({0x17643a0, 0x28cbbc0})
        /toolchain/go/src/runtime/panic.go:890 +0x262
github.com/siderolabs/sidero/app/sidero-controller-manager/internal/metadata.labelNodes({0xc000cd2000, 0x1657, 0x1b00}, {0xc0007f4330, 0x24})
        /src/app/sidero-controller-manager/internal/metadata/metadata_server.go:297 +0x165
github.com/siderolabs/sidero/app/sidero-controller-manager/internal/metadata.(*metadataConfigs).FetchConfig(0xc0003ac260, {0x1c1eb20, 0xc0002da0e0}, 0xc000af4d00?)
        /src/app/sidero-controller-manager/internal/metadata/metadata_server.go:228 +0x5f2
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1c1eb20?, 0xc0002da0e0?}, 0x203000?)
        /toolchain/go/src/net/http/server.go:2109 +0x2f
net/http.(*ServeMux).ServeHTTP(0xc000aa48e0?, {0x1c1eb20, 0xc0002da0e0}, 0xc000af4d00)
        /toolchain/go/src/net/http/server.go:2487 +0x149
main.main.func7.1({0x1c1eb20?, 0xc0002da0e0?}, 0xc0007fdbc0?)
        /src/app/sidero-controller-manager/main.go:307 +0xa5
net/http.HandlerFunc.ServeHTTP(0x203000?, {0x1c1eb20?, 0xc0002da0e0?}, 0xc0002da0e0?)
        /toolchain/go/src/net/http/server.go:2109 +0x2f
golang.org/x/net/http2/h2c.h2cHandler.ServeHTTP({{0x1c0b700?, 0xc0003be1c8?}, 0xc0006a6000?}, {0x1c1eb20, 0xc0002da0e0}, 0xc000af4d00)
        /.cache/mod/golang.org/x/net@v0.4.0/http2/h2c/h2c.go:125 +0x59b
net/http.serverHandler.ServeHTTP({0xc0007fdb90?}, {0x1c1eb20, 0xc0002da0e0}, 0xc000af4d00)
        /toolchain/go/src/net/http/server.go:2947 +0x30c
net/http.(*conn).serve(0xc0002b0280, {0x1c1fcb8, 0xc0006703f0})
        /toolchain/go/src/net/http/server.go:1991 +0x607
created by net/http.(*Server).Serve
        /toolchain/go/src/net/http/server.go:3102 +0x4db
```

### PR DESCRIPTION
**Pull request by smira**
Previous PR used Talos machinery to load the config, and then generate config patch to patch the config. This worked fine until Talos started validating loaded machine config for 'unknown fields'. This breaks this flow, as Omni Talos machinery version should be >= Talos version.

Rewriting the code to skip loading using Talos machinery, also handle cases of broken config without `machine` or `machine.kubelet` sections. These will probably be invalid anyways, but we let Talos report it instead of panic in Sidero.

Fixes #1076

Also use Talos machinery configpatcher to reduce code duplication.

And, last but not the least, add a unit-test for the metadata server, which covers all major code paths.

```
ok  	github.com/siderolabs/sidero/app/sidero-controller-manager/internal/metadata	0.022s	coverage: 72.8% of statements
```

### CODE REVIEW

File: app/sidero-controller-manager/internal/metadata/metadata_server.go [hunk 1]
```diff
@@ -251,62 +249,102 @@ func patchConfigs(decodedData []byte, patches []metalv1.ConfigPatches) ([]byte,
...
+				Path: "/machine",
+				Op:   "add",
+			}
 
-		if _, ok = kubeletExtraArgs["node-labels"]; ok {
-			kubeletExtraArgs["node-labels"] += fmt.Sprintf(",metal.sidero.dev/uuid=%s", serverName)
-		} else {
-			kubeletExtraArgs["node-labels"] = fmt.Sprintf("metal.sidero.dev/uuid=%s", serverName)
+			patchValue = map[string]any{
+				"kubelet": map[string]any{
```
Comment (frezbo) [inline app/sidero-controller-manager/internal/metadata/metadata_server.go:305]: machine.nodeLabels is better?

**Review by frezbo — APPROVED** [review]

File: app/sidero-controller-manager/internal/metadata/metadata_server.go (hunk 1 above)
Comment (smira) [reply app/sidero-controller-manager/internal/metadata/metadata_server.go:305]: it is, but not supported on all versions of Talos, I don't want to lock in to >= 1.3
