### PR TITLE
fix: update HTTP boot filename

### LINKED ISSUE #1295: proxy DCHP sends out http url that returns 404
The returned URL is not accessible, see screenshot. CAPI and sidero metal on latest releases as of today.

`sudo tcpdump -i eth0 port 67 or port 68 -e -n -vv` on the same network:
```
06:57:11.522704 bc:24:11:b7:db:31 > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 382: (tos 0x0, ttl 64, id 23608, offset 0, flags [none], proto UDP (17), length 368)
    0.0.0.0.68 > 255.255.255.255.67: [udp sum ok] BOOTP/DHCP, Request from bc:24:11:b7:db:31, length 340, xid 0x18e0aaa4, Flags [Broadcast] (0x8000)
          Client-Ethernet-Address bc:24:11:b7:db:31
          Vendor-rfc1048 Extensions
            Magic Cookie 0x63825363
            DHCP-Message (53), length 1: Discover
            MSZ (57), length 2: 1472
            Parameter-Request (55), length 27:
              Subnet-Mask (1), Time-Zone (2), Default-Gateway (3), Time-Server (4)
              IEN-Name-Server (5), Domain-Name-Server (6), Hostname (12), BS (13)
              Domain-Name (15), RP (17), EP (18), RSZ (22)
              TTL (23), BR (28), YD (40), YS (41)
              NTP (42), Vendor-Option (43), Requested-IP (50), Lease-Time (51)
              Server-ID (54), RN (58), RB (59), Vendor-Class (60)
              Unknown (234), BF (67), GUID (97)
            GUID (97), length 17: 0.53.220.220.148.224.159.19.79.190.147.29.87.161.125.58.243
            NDI (94), length 3: 1.3.1
            ARCH (93), length 2: 16
            Vendor-Class (60), length 33: "HTTPClient:Arch:00016:UNDI:003001"
06:57:11.522976 de:71:f6:22:76:8b > ff:ff:ff:ff:ff:ff, ethertype IPv4 (0x0800), length 378: (tos 0x0, ttl 64, id 61580, offset 0, flags [DF], proto UDP (17), length 364)
    192.168.50.50.67 > 255.255.255.255.68: [bad udp cksum 0xf443 -> 0x7126!] BOOTP/DHCP, Reply, length 336, xid 0x18e0aaa4, Flags [Broadcast] (0x8000)
          Server-IP 192.168.50.50
          Client-Ethernet-Address bc:24:11:b7:db:31
          Vendor-rfc1048 Extensions
            Magic Cookie 0x63825363
            Vendor-Class (60), length 33: "HTTPClient:Arch:00016:UNDI:003001"
            BF (67), length 39: "http://192.168.50.50:8081/tftp/snp.ipxe"
            GUID (97), length 17: 0.53.220.220.148.224.159.19.79.190.147.29.87.161.125.58.243
```
image

```
curl http://192.168.50.50:8081/tftp/snp.ipxe
404 page not found
```

### PR DESCRIPTION
**Pull request by smira**
We need to use EFI version of iPXE.

Fixes #1295

### CODE REVIEW

**Review by utkuozdemir — APPROVED** [review]

File: app/sidero-controller-manager/internal/dhcp/dhcp_server.go [hunk 1]
```diff
@@ -180,10 +180,10 @@ func offerDHCP(req *dhcpv4.DHCPv4, apiEndpoint string, apiPort int, fwtype Firmw
 		resp.UpdateOption(dhcpv4.OptBootFileName("snp-arm64.efi"))
 	case FirmwareX86HTTP:
 		// This is completely standard HTTP-boot: just load a file from HTTP.
-		resp.UpdateOption(dhcpv4.OptBootFileName(fmt.Sprintf("http://%s/tftp/snp.ipxe", net.JoinHostPort(serverIP.String(), strconv.Itoa(apiPort)))))
```
Comment (smira) [inline app/sidero-controller-manager/internal/dhcp/dhcp_server.go:183]: this file was never present actually
